import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import Components
import Header from "@/src/components/Header";
import { FooterWithSocialLinks } from "@/src/components/FooterWithSocialLinks";
import { QueryProvider } from "../components/QueryProvider";
import { Toaster } from "@/components/ui/sonner"
import { AccountResType, AccountType } from "../schemas/account.schema";
import authApi from "../apis/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // let user: AccountType | null = null;


  return (
    <>
      <html lang="en" className="mdl-js">
        <body
          data-new-gr-c-s-check-loaded="14.1229.0"
          data-gr-ext-installed=""
        >
          <QueryProvider>
            <Header />
            {children}
            <FooterWithSocialLinks></FooterWithSocialLinks>
          </QueryProvider>
          <Toaster  position="bottom-left" richColors  />
        </body>
      </html>
    </>
  );
}
